name: pheonyx
description: "seamlessly control your devices"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pheonyx_frb_client:
    path: rust_builder
  flutter_rust_bridge: 2.9.0
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  freezed_annotation: ^3.0.0
  multicast_dns: ^0.3.3
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  change_app_package_name: ^1.5.0
  freezed: ^3.0.4
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
