// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> startMdnsServer({int? dur}) =>
    RustLib.instance.api.crateApiMdnsStartMdnsServer(dur: dur);

MdnsServer createMdnsServer() =>
    RustLib.instance.api.crateApiMdnsCreateMdnsServer();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< MdnsServer>>
abstract class MdnsServer implements RustOpaqueInterface {}
