// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UdpClient>>
abstract class UdpClient implements RustOpaqueInterface {
  Future<void> connect({required int port, required String ip});

  factory UdpClient() => RustLib.instance.api.crateApiUdpClientUdpClientNew();

  Future<String> receiveMessage();

  Future<void> sendMessage({required String message});
}
